INSERT INTO PLAYER ("ID", "BIRTHDATE", "BIRTHPLACE","IMAGE","JERSEY","NAME","POSITION","STICK","SURENAME") VALUES ('1', DATE '1985-01-01','Prachatice','/myimage.jpg','4','Jan','0','1','Novak');
INSERT INTO TEAM ("ID", "LOGO","NAME") VALUES ('1','pathToLogo','Team 1');
INSERT INTO TEAM ("ID", "LOGO","NAME") VALUES ('2','pathToLogo 2','Team 2');
INSERT INTO SEASON ("ID","NAME","YEARS") VALUES ('1','importedSeasonName','2016/2017');
INSERT INTO SEASON_TEAM_PLAYER ("ID","PLAYER_ID","TEAM_ID","SEASON_ID") VALUES (1,1,1,1);
INSERT INTO SEASON_TEAM_PLAYER ("ID","PLAYER_ID","TEAM_ID","SEASON_ID") VALUES (2,1,2,1);