INSERT INTO TEAM ("ID", "LOGO","NAME") VALUES ('1','pathToLogo','Team 1');
INSERT INTO TEAM ("ID", "LOGO","NAME") VALUES ('2','pathToLogo2','Team 2');
INSERT INTO SEASON ("ID","NAME","YEARS") VALUES ('1','importedSeasonName','2016/2017');
INSERT INTO GAME ("ID","SEASON_ID","AWAYSCORE","HOMESCORE","DATE","AWAYTEAM","HOMETEAM") VALUES ('1','1','1','2',CURRENT_DATE, 2,1);
INSERT INTO GAME ("ID","SEASON_ID","AWAYSCORE","HOMESCORE","DATE","AWAYTEAM","HOMETEAM") VALUES ('2','1','2','1',CURRENT_DATE, 1,2);